#!/usr/bin/env python3
"""Scan tracked repository text files for potentially restrictive license text."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_REPORT = ROOT / "docs" / "compliance" / "repo_license_text_scan.md"

PATTERNS: dict[str, re.Pattern[str]] = {
    "gpl_reference": re.compile(r"gnu\s+(general\s+public\s+license|gpl)", re.IGNORECASE),
    "agpl_reference": re.compile(r"affero\s+general\s+public\s+license|agpl", re.IGNORECASE),
    "lgpl_reference": re.compile(r"lesser\s+general\s+public\s+license|lgpl", re.IGNORECASE),
    "copyleft_keyword": re.compile(r"\bcopyleft\b", re.IGNORECASE),
    "all_rights_reserved": re.compile(r"all\s+rights\s+reserved", re.IGNORECASE),
}

SKIP_FILES = {"docs/compliance/repo_license_text_scan.md", "docs/compliance/secret_scan_report.md"}

SKIP_SUFFIXES = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".ttf", ".eot", ".pdf", ".zip", ".gz", ".sqlite", ".db",
}


def tracked_files() -> list[Path]:
    output = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    files: list[Path] = []
    for rel in output.splitlines():
        if rel in SKIP_FILES:
            continue
        path = ROOT / rel
        if path.suffix.lower() in SKIP_SUFFIXES:
            continue
        files.append(path)
    return files


def scan() -> dict[str, list[tuple[str, int, str]]]:
    findings: dict[str, list[tuple[str, int, str]]] = {key: [] for key in PATTERNS}

    for file_path in tracked_files():
        try:
            text = file_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        rel = file_path.relative_to(ROOT).as_posix()
        for idx, line in enumerate(text.splitlines(), start=1):
            for key, pattern in PATTERNS.items():
                if pattern.search(line):
                    findings[key].append((rel, idx, line.strip()))

    return findings


def build_report(findings: dict[str, list[tuple[str, int, str]]]) -> str:
    total_hits = sum(len(values) for values in findings.values())
    lines = [
        "# Repository license-text scan",
        "",
        "Generated by `scripts/compliance/repo_license_text_scan.py`.",
        "",
        "## Summary",
        f"- Patterns scanned: **{len(PATTERNS)}**",
        f"- Total matches: **{total_hits}**",
        "",
    ]

    for key, matches in findings.items():
        lines.append(f"## {key}")
        if not matches:
            lines.append("- No matches.")
            lines.append("")
            continue

        lines.append("| File | Line | Snippet |")
        lines.append("|---|---:|---|")
        for rel, line_no, snippet in matches:
            short = snippet.replace("|", "\\|")
            if len(short) > 140:
                short = short[:137] + "..."
            lines.append(f"| `{rel}` | {line_no} | {short} |")
        lines.append("")

    lines.extend(
        [
            "## Notes",
            "- Matches are heuristic and may include policy docs or false positives.",
            "- Any match in executable source should be reviewed before release.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    findings = scan()
    report = build_report(findings)
    OUT_REPORT.write_text(report + "\n", encoding="utf-8")
    print(f"wrote {OUT_REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
