#!/usr/bin/env python3
"""Scan tracked repository files for likely secrets before open-source release."""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT_REPORT = ROOT / "docs" / "compliance" / "secret_scan_report.md"

SECRET_PATTERNS: dict[str, re.Pattern[str]] = {
    "private_key_block": re.compile(r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"),
    "aws_access_key": re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    "github_token": re.compile(r"\bgh[pousr]_[A-Za-z0-9]{36,}\b"),
    "slack_token": re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{10,}\b"),
    "generic_api_key_assignment": re.compile(
        r"(?i)\b(api[_-]?key|secret|token|password)\b\s*[:=]\s*['\"][^'\"]{12,}['\"]"
    ),
}

SKIP_SUFFIXES = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".woff", ".woff2", ".ttf", ".eot", ".pdf", ".zip", ".gz", ".sqlite", ".db",
}


def tracked_files() -> list[Path]:
    output = subprocess.check_output(["git", "ls-files"], cwd=ROOT, text=True)
    return [ROOT / rel for rel in output.splitlines() if (ROOT / rel).suffix.lower() not in SKIP_SUFFIXES]


def scan() -> dict[str, list[tuple[str, int, str]]]:
    findings: dict[str, list[tuple[str, int, str]]] = {name: [] for name in SECRET_PATTERNS}

    for file_path in tracked_files():
        try:
            text = file_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue

        rel = file_path.relative_to(ROOT).as_posix()
        for line_no, line in enumerate(text.splitlines(), start=1):
            for name, pattern in SECRET_PATTERNS.items():
                if pattern.search(line):
                    snippet = line.strip()
                    if len(snippet) > 140:
                        snippet = snippet[:137] + "..."
                    findings[name].append((rel, line_no, snippet))

    return findings


def build_report(findings: dict[str, list[tuple[str, int, str]]]) -> str:
    total = sum(len(v) for v in findings.values())
    lines = [
        "# Secret scan report",
        "",
        "Generated by `scripts/compliance/secret_scan.py`.",
        "",
        "## Summary",
        f"- Patterns scanned: **{len(SECRET_PATTERNS)}**",
        f"- Total potential matches: **{total}**",
        "",
    ]

    for name, matches in findings.items():
        lines.append(f"## {name}")
        if not matches:
            lines.append("- No matches.")
            lines.append("")
            continue

        lines.append("| File | Line | Snippet |")
        lines.append("|---|---:|---|")
        for rel, line_no, snippet in matches:
            safe = snippet.replace("|", "\\|")
            lines.append(f"| `{rel}` | {line_no} | {safe} |")
        lines.append("")

    lines.extend(
        [
            "## Notes",
            "- Matches are heuristic and may include test fixtures/placeholders.",
            "- Confirm each finding is non-sensitive before public release.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    findings = scan()
    report = build_report(findings)
    OUT_REPORT.write_text(report + "\n", encoding="utf-8")
    print(f"wrote {OUT_REPORT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
