import { defineStore } from 'pinia'
import api from '../services/api'
import { setActionStatus, setActionError } from '../helpers/actionStatus'
import { deriveSelectedId } from '../helpers/selection'
import { toResourceError } from '../helpers/apiErrors'
import { useAuthStore } from './authStore'