from __future__ import annotations

from typing import Any, Protocol

from .types import AIPipelineRequest


class AIPipelineServiceInterface(Protocol):
    def run(self, request: AIPipelineRequest) -> dict[str, Any]: ...
    def run_interaction(self, prompt: str, context: dict[str, Any] | None = None, **metadata: Any) -> dict[str, Any]: ...
    def generate_text(self, text: str, model_name: str) -> dict[str, Any]: ...
    def provider_health(self) -> dict[str, Any]: ...
    def list_available_models(self) -> dict[str, Any]: ...


class AIProviderInterface(Protocol):
    def __call__(self, messages: list[dict[str, str]], *, max_new_tokens: int) -> list[dict[str, Any]]: ...


class AIProviderFactoryInterface(Protocol):
    def __call__(self, model_id: str) -> AIProviderInterface: ...


class ProviderModelSelectionResolverInterface(Protocol):
    def __call__(self, payload: dict[str, Any], ai_service: AIPipelineServiceInterface, **kwargs: Any) -> dict[str, str]: ...


class CatalogModelSelectionResolverInterface(Protocol):
    def __call__(self, **kwargs: Any) -> dict[str, str]: ...
