from __future__ import annotations

from typing import Any, Protocol

from .types import AIPipelineConfig, AIPipelineRequest


class AIProviderInterface(Protocol):
    def generate(self, prompt: str, system_prompt: str, context: dict[str, Any]) -> dict[str, Any]: ...
    def invoke(self, prompt: str, context: dict[str, Any]) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
    def inventory(self) -> list[dict[str, Any]]: ...
    def name(self) -> str: ...


class AIProviderFactoryInterface(Protocol):
    def __call__(self, config: AIPipelineConfig, *, provider: str, model_id: str) -> AIProviderInterface: ...


class AIPipelineServiceInterface(Protocol):
    def run(self, request: AIPipelineRequest) -> dict[str, Any]: ...
    def run_interaction(self, prompt: str, context: dict[str, Any] | None = None, **metadata: Any) -> dict[str, Any]: ...
    def provider_health(self) -> dict[str, Any]: ...
    def list_available_models(self) -> dict[str, Any]: ...
